### ISSUE TITLE
Add v1.3.0 tag/release

### ISSUE THREAD

**Issue by jbaum98** [toastdriven/pylev#10]
I notice that the version on Pypi is `1.3.0` and the version in the README says `1.3.0` as of commit 72e3d490515c3188e2acac9c15ea1b466f9ff938, but there isn't a Github release or a tag for `v1.3.0`. Can you add one? I'm packaging (NixOS/nixpkgs#53599) this for nixpkgs and it would be helpful.

**Comment by toastdriven** [comment]
Sorry this took forever. There's a `v1.3.0` tag there now & there will be a `v1.4.0` there soon that reflects `main`. Thanks & apologies again.
