### ISSUE TITLE
This project is active?

### ISSUE THREAD

**Issue by eamanu** [toastdriven/pylev#12]
Hi, I note that this project is used on clikit and is a depedency of poetry. 

I'm trying to package poetry on Debian and I need package pylev too. I was 
wondering to know if this project is still maintained.

Cheers

**Comment by toastdriven** [comment]
Yes, it is still maintained, though I've had to take a break from it for the last couple months. I'll be plowing through the backlog of issues in the next month.

**Comment by eamanu** [comment]
Sorry for the delay. Thanks! Good to know
